---
default:
  pipeline:
    Cloud-provider:
      - name: "Azure resource group name"
        description: "The name of the resource group in which create the resources"
        key: azure_resource_group_name
        widget: simple_text
        type: string
        default: "cycloid-demo"
      - name: "Azure environment"
        description: "The Cloud Environment which should be used"
        key: azure_env
        widget: radios
        type: string
        values:
          - public
          - china
          - german
          - stack
          - usgovernment
        default: public
      - name: "Azure location"
        key: azure_location
        widget: auto_complete
        type: string
        values:
          [
            eastasia,
            southeastasia,
            centralus,
            eastus,
            eastus2,
            westus,
            northcentralus,
            southcentralus,
            northeurope,
            westeurope,
            japanwest,
            japaneast,
            brazilsouth,
            australiaeast,
            australiasoutheast,
            southindia,
            centralindia,
            westindia,
            canadacentral,
            canadaeast,
            uksouth,
            ukwest,
            westcentralus,
            westus2,
            koreacentral,
            koreasouth,
            francecentral,
            francesouth,
            australiacentral,
            australiacentral2,
            uaecentral,
            uaenorth,
            southafricanorth,
            southafricawest,
            switzerlandnorth,
            switzerlandwest,
            germanynorth,
            germanywestcentral,
            norwaywest,
            norwayeast,
          ]
        default: francecentral
      - name: "Azure subscription id"
        description: "The Subscription ID which should be used"
        key: azure_subscription_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.subscription_id))"
      - name: "Azure tenant id"
        description: "The Tenant ID which should be used"
        key: azure_tenant_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.tenant_id))"
      - name: "Azure client id"
        description: "The Client ID which should be used"
        key: azure_client_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.client_id))"
      - name: "Azure client secret"
        description: "The Client Secret which should be used"
        key: azure_client_secret
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.client_secret))"
    Application-code:
      - name: "Application git public url"
        description: "The url of the public GIT repository containing the source code of the application"
        key: code_git_public_repository
        widget: simple_text
        type: string
        default: "https://github.com/cycloid-community-catalog/docs-step-by-step-stack"
      - name: "Application git repository branch"
        description: "The branch of the public GIT repository containing the source code of the application"
        key: code_git_branch
        widget: simple_text
        type: string
        default: code
    Private-stack:
      - name: "Service catalog repository"
        description: "Service catalog repository containing your private stack"
        key: git_repository
        widget: cy_scs
        type: string
        default: git@github.com:zepouet/my-cycloid-stack.git
      - name: "Service catalog branch"
        description: "Branch to use containing the source code of your stack"
        key: stack_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: azure
      - name: "Config catalog branch"
        description: "Branch to use which will contain the Configuration of your environment"
        key: config_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: config
      - name: "Service catalog repository credential (SSH key)"
        description: "Credential (SSH key) used to fetch the service catalog of the stack"
        key: git_ssh_key
        widget: cy_cred
        type: string
        default: "((ssh_key.ssh_key))"
    Terraform:
      - name: "Terraform Azure storage account name"
        description: "Azure account storage used to store Terraform tfstate file"
        key: terraform_storage_account_name
        widget: cy_cred
        type: string
        default: "((azure_storage_step-by-step.account_name))"
      - name: "Terraform Azure storage access key"
        description: "Azure storage access key used to store Terraform tfstate file"
        key: terraform_storage_access_key
        widget: cy_cred
        type: string
        default: "((azure_storage_step-by-step.access_key))"
      - name: "Azure storage container name"
        description: "Azure storage container name used to store Terraform tfstate file"
        key: terraform_storage_container_name
        widget: simple_text
        type: string
        default: "cycloid-demo"
      - name: "Azure storage container path"
        description: "Azure storage container path used to store Terraform tfstate file"
        key: terraform_storage_container_path
        widget: simple_text
        type: string
        default: "($ project $)/($ environment $)"
    Cycloid-API:
      - name: "Cycloid api url"
        description: "Url of the Cycloid API to use"
        key: api_url
        widget: simple_text
        type: string
        default: https://http-api.cycloid.io
      - name: "Cycloid api key"
        key: api_key
        widget: cy_cred
        type: string
        default: "((custom_cyclobot-api-key.key))"

  terraform:
    configuration:
      - name: "Azure subnet id"
        description: "Subnet on which you want to create the instance. It should look like: /subscriptions/.../subnets/default"
        key: subnet_id
        widget: simple_text
        type: string
        required: true
      - name: "Azure instance type"
        description: "The type of instance you want to create"
        key: instance_type
        widget: slider_list
        type: string
        values:
          - Standard_DS1_v2
          - Standard_DS2_v2
          - Standard_DS3_v2
        default: Standard_DS1_v2
